# Generated by Django 3.1.4 on 2020-12-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201214_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spends',
            options={'ordering': ['cost_date']},
        ),
    ]
