---
default:
  SECRET_KEY: 12345
  GOOGLE_OAUTH2_SECRET: 12345
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: 12345
  EMAIL_HOST_USER: 12345
  EMAIL_HOST_PASSWORD: 12345
  DEBUG: False
  ALLOWED_HOSTS: []

development:
  DEBUG: True
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: home_bookkeeping
      USER: django_user
      PASSWORD: password
      HOST: 127.0.0.1
      PORT: 5432