---
default:
  SECRET_KEY: null

  DEBUG: False
  ALLOWED_HOSTS: []

  INSTALLED_APPS:
    - django_filters
    - social_django
    - accounts.apps.AccountsConfig
    - expenses.apps.ExpensesConfig
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
  
  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - whitenoise.middleware.WhiteNoiseMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware
  
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: ["@format {this.BASE_DIR}/templates"]
      APP_DIRS: true
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages
          - social_django.context_processors.backends
          - social_django.context_processors.login_redirect
  
  ROOT_URLCONF: home_bookkeeping.urls

  WSGI_APPLICATION: home_bookkeeping.wsgi.application

  AUTHENTICATION_BACKENDS:
    - social_core.backends.google.GoogleOAuth2
    - django.contrib.auth.backends.ModelBackend
  
  SOCIAL_AUTH_PIPELINE:
    - social_core.pipeline.social_auth.social_details
    - social_core.pipeline.social_auth.social_uid
    - social_core.pipeline.social_auth.social_user
    - social_core.pipeline.user.get_username
    - social_core.pipeline.social_auth.associate_by_email
    - social_core.pipeline.user.create_user
    - social_core.pipeline.social_auth.associate_user
    - social_core.pipeline.social_auth.load_extra_data
    - social_core.pipeline.user.user_details
    - accounts.pipeline.save_to_group
  
    # Password validation
  # https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator
  
  # Internationalization
  # https://docs.djangoproject.com/en/3.1/topics/i18n/
  LANGUAGE_CODE: en-us
  TIME_ZONE: Asia/Yekaterinburg
  USE_I18: True
  USE_L10: True
  USE_T: True

  # login actions
  LOGIN_REDIRECT_URL: /expenses/
  LOGOUT_REDIRECT_URL: login

  GOOGLE_OAUTH2_SECRET: null
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: null

  EMAIL_HOST: smtp.mailgun.org
  EMAIL_PORT: 587
  EMAIL_USE_TLS: True
  DEFAULT_FROM_EMAIL: support@homebookkeeping.com
  EMAIL_HOST_USER:  null
  EMAIL_HOST_PASSWORD: null

  # Static files (CSS, JavaScript, Images)
  # https://docs.djangoproject.com/en/3.1/howto/static-files/
  STATIC_ROOT: "@format {this.BASE_DIR}/staticfiles"
  STATIC_URL: /static/

development:
  DEBUG: True
  ALLOWED_HOSTS: ['*']
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: null
      USER: null
      PASSWORD: null
      HOST: null
      PORT: null


heroku:
  DEBUG: False
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - homebookkeeping.herokuapp.com
  CSRF_COOKIE_SECURE: True
  SESSION_COOKIE_SECURE: True

github:
  DEBUG: True
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: github_actions
      USER: postgres
      PASSWORD: postgres
      HOST: localhost
      PORT: 5432