---
default:
  SECRET_KEY: null

  GOOGLE_OAUTH2_SECRET: null
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: null

  EMAIL_HOST: smtp.mailgun.org
  EMAIL_PORT: 587
  EMAIL_USE_TLS: True
  DEFAULT_FROM_EMAIL: support@homebookkeeping.com
  EMAIL_HOST_USER:  null
  EMAIL_HOST_PASSWORD: null

  DEBUG: False
  ALLOWED_HOSTS: []

development:
  DEBUG: True
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: null
      USER: null
      PASSWORD: null
      HOST: null
      PORT: null


heroku:
  DEBUG: False
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - homebookkeeping.herokuapp.com
  CSRF_COOKIE_SECURE: True
  SESSION_COOKIE_SECURE: True

github:
  DEBUG: True
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: github_actions
      USER: postgres
      PASSWORD: postgres
      HOST: localhost
      PORT: 5432