name: Python Master Workflow
on:
  push:
    branches:
      - 'develop'
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        env: DJANGO_SECRET_KEY: 123
        run: |
          pip install coverage
          pip install -r requirements.txt
          cd home_bookkeeping
          coverage run manage.py test
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
